# Generated by Django 5.1 on 2024-09-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gk_app", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTP",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("otp", models.CharField(max_length=255, null=True)),
                ("userId", models.CharField(max_length=255, null=True)),
                ("userPhone", models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="registration",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("userName", models.CharField(max_length=300)),
                ("mobileNo", models.CharField(max_length=10)),
                ("aadharNo", models.CharField(default="NULL", max_length=12)),
                ("native", models.CharField(default="NULL", max_length=300)),
                ("password", models.CharField(max_length=300)),
                ("roleId", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("userName", models.CharField(max_length=255, null=True)),
                ("userEmail", models.CharField(max_length=255, null=True)),
                ("userPhone", models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="super_admin_details",
        ),
    ]
